@echo off
REM ===================================================
REM BITTEN EA Setup for 3 MT5 Instances
REM Automatically configures 3 MT5 terminals with EA
REM ===================================================

echo =========================================
echo BITTEN EA Multi-Instance Setup v1.0
echo =========================================
echo.

REM Check if EA file exists
if not exist "BITTENBridge_v3_ENHANCED.mq5" (
    echo ERROR: BITTENBridge_v3_ENHANCED.mq5 not found!
    echo Please download it first using:
    echo powershell -c "wget http://134.199.204.67:8888/static/BITTENBridge_v3_ENHANCED.mq5 -O BITTENBridge_v3_ENHANCED.mq5"
    pause
    exit /b 1
)

REM Create BITTEN directories
echo Creating BITTEN directories...
mkdir C:\BITTEN_Bridge\Instance1 2>nul
mkdir C:\BITTEN_Bridge\Instance2 2>nul
mkdir C:\BITTEN_Bridge\Instance3 2>nul
mkdir C:\BITTEN_Bridge\Logs 2>nul

REM Find MT5 installations
echo.
echo Searching for MT5 installations...
set MT5_COUNT=0

REM Common MT5 installation paths
set PATHS[0]=%APPDATA%\MetaQuotes\Terminal
set PATHS[1]=C:\Program Files\MetaTrader 5
set PATHS[2]=C:\Program Files (x86)\MetaTrader 5
set PATHS[3]=C:\MetaTrader 5
set PATHS[4]=D:\MetaTrader 5

REM Search for terminal folders
for /d %%D in ("%APPDATA%\MetaQuotes\Terminal\*") do (
    if exist "%%D\MQL5\Experts" (
        set /a MT5_COUNT+=1
        set MT5_PATH[!MT5_COUNT!]=%%D
        echo Found MT5 !MT5_COUNT!: %%D
    )
)

if %MT5_COUNT% LSS 3 (
    echo.
    echo WARNING: Only found %MT5_COUNT% MT5 installations!
    echo You need 3 separate MT5 terminals installed.
    echo.
    echo To install multiple MT5 instances:
    echo 1. Download MT5 installer
    echo 2. Install to different folders:
    echo    - C:\MT5_Instance1
    echo    - C:\MT5_Instance2
    echo    - C:\MT5_Instance3
    echo.
    pause
)

REM Copy EA to each instance
echo.
echo Copying EA to MT5 instances...

REM Instance 1 - Nibbler/Fang
if defined MT5_PATH[1] (
    echo Configuring Instance 1 (Nibbler/Fang)...
    copy /Y "BITTENBridge_v3_ENHANCED.mq5" "!MT5_PATH[1]!\MQL5\Experts\BITTEN_Instance1.mq5"
    
    REM Create configuration file
    (
        echo // BITTEN Instance 1 Configuration
        echo // Tier: Nibbler/Fang
        echo #define INSTANCE_ID 1
        echo #define CUSTOM_MAGIC 20250626
        echo #define MAX_RISK 2.0
        echo #define MAX_DAILY_TRADES 10
        echo #define FILES_PREFIX "bitten1_"
    ) > "!MT5_PATH[1]!\MQL5\Include\BITTEN_Config1.mqh"
)

REM Instance 2 - Commander
if defined MT5_PATH[2] (
    echo Configuring Instance 2 (Commander)...
    copy /Y "BITTENBridge_v3_ENHANCED.mq5" "!MT5_PATH[2]!\MQL5\Experts\BITTEN_Instance2.mq5"
    
    (
        echo // BITTEN Instance 2 Configuration
        echo // Tier: Commander
        echo #define INSTANCE_ID 2
        echo #define CUSTOM_MAGIC 20250627
        echo #define MAX_RISK 3.0
        echo #define MAX_DAILY_TRADES 20
        echo #define FILES_PREFIX "bitten2_"
    ) > "!MT5_PATH[2]!\MQL5\Include\BITTEN_Config2.mqh"
)

REM Instance 3 - APEX
if defined MT5_PATH[3] (
    echo Configuring Instance 3 (APEX)...
    copy /Y "BITTENBridge_v3_ENHANCED.mq5" "!MT5_PATH[3]!\MQL5\Experts\BITTEN_Instance3.mq5"
    
    (
        echo // BITTEN Instance 3 Configuration
        echo // Tier: APEX
        echo #define INSTANCE_ID 3
        echo #define CUSTOM_MAGIC 20250628
        echo #define MAX_RISK 5.0
        echo #define MAX_DAILY_TRADES 50
        echo #define FILES_PREFIX "bitten3_"
    ) > "!MT5_PATH[3]!\MQL5\Include\BITTEN_Config3.mqh"
)

REM Create launcher scripts
echo.
echo Creating launcher scripts...

REM Instance 1 Launcher
(
    echo @echo off
    echo echo Starting BITTEN Instance 1 (Nibbler/Fang)...
    echo cd /d "!MT5_PATH[1]!"
    echo start terminal64.exe /config:Config\BITTEN1.ini
    echo echo Instance 1 started. Check C:\BITTEN_Bridge\Instance1 for files.
) > "Launch_Instance1.bat"

REM Instance 2 Launcher
(
    echo @echo off
    echo echo Starting BITTEN Instance 2 (Commander)...
    echo cd /d "!MT5_PATH[2]!"
    echo start terminal64.exe /config:Config\BITTEN2.ini
    echo echo Instance 2 started. Check C:\BITTEN_Bridge\Instance2 for files.
) > "Launch_Instance2.bat"

REM Instance 3 Launcher
(
    echo @echo off
    echo echo Starting BITTEN Instance 3 (APEX)...
    echo cd /d "!MT5_PATH[3]!"
    echo start terminal64.exe /config:Config\BITTEN3.ini
    echo echo Instance 3 started. Check C:\BITTEN_Bridge\Instance3 for files.
) > "Launch_Instance3.bat"

REM Create Python integration helper
echo.
echo Creating Python integration helper...

(
    echo # BITTEN MT5 Bridge Configuration
    echo # Auto-generated by setup script
    echo.
    echo MT5_INSTANCES = {
    echo     'instance1': {
    echo         'tier': 'nibbler_fang',
    echo         'path': r'C:\BITTEN_Bridge\Instance1',
    echo         'magic': 20250626,
    echo         'max_risk': 2.0,
    echo         'max_daily_trades': 10,
    echo         'files': {
    echo             'instructions': 'bitten1_instructions_secure.txt',
    echo             'results': 'bitten1_results_secure.txt',
    echo             'status': 'bitten1_status_secure.txt',
    echo             'positions': 'bitten1_positions_secure.txt',
    echo             'account': 'bitten1_account_secure.txt',
    echo             'market': 'bitten1_market_secure.txt'
    echo         }
    echo     },
    echo     'instance2': {
    echo         'tier': 'commander',
    echo         'path': r'C:\BITTEN_Bridge\Instance2',
    echo         'magic': 20250627,
    echo         'max_risk': 3.0,
    echo         'max_daily_trades': 20,
    echo         'files': {
    echo             'instructions': 'bitten2_instructions_secure.txt',
    echo             'results': 'bitten2_results_secure.txt',
    echo             'status': 'bitten2_status_secure.txt',
    echo             'positions': 'bitten2_positions_secure.txt',
    echo             'account': 'bitten2_account_secure.txt',
    echo             'market': 'bitten2_market_secure.txt'
    echo         }
    echo     },
    echo     'instance3': {
    echo         'tier': 'apex',
    echo         'path': r'C:\BITTEN_Bridge\Instance3',
    echo         'magic': 20250628,
    echo         'max_risk': 5.0,
    echo         'max_daily_trades': 50,
    echo         'files': {
    echo             'instructions': 'bitten3_instructions_secure.txt',
    echo             'results': 'bitten3_results_secure.txt',
    echo             'status': 'bitten3_status_secure.txt',
    echo             'positions': 'bitten3_positions_secure.txt',
    echo             'account': 'bitten3_account_secure.txt',
    echo             'market': 'bitten3_market_secure.txt'
    echo         }
    echo     }
    echo }
) > "mt5_config.py"

REM Create monitoring script
(
    echo @echo off
    echo :loop
    echo cls
    echo =========================================
    echo BITTEN MT5 Monitor
    echo =========================================
    echo.
    echo Instance 1 Files:
    echo -----------------
    dir /b C:\BITTEN_Bridge\Instance1\*.txt 2^>nul
    echo.
    echo Instance 2 Files:
    echo -----------------
    dir /b C:\BITTEN_Bridge\Instance2\*.txt 2^>nul
    echo.
    echo Instance 3 Files:
    echo -----------------
    dir /b C:\BITTEN_Bridge\Instance3\*.txt 2^>nul
    echo.
    echo Press Ctrl+C to exit
    timeout /t 5 ^>nul
    goto loop
) > "Monitor_BITTEN.bat"

REM Create README
(
    echo BITTEN Multi-Instance Setup Complete!
    echo =====================================
    echo.
    echo File Structure:
    echo - C:\BITTEN_Bridge\Instance1 - Nibbler/Fang trades
    echo - C:\BITTEN_Bridge\Instance2 - Commander trades  
    echo - C:\BITTEN_Bridge\Instance3 - APEX trades
    echo.
    echo Next Steps:
    echo 1. Open each MT5 terminal
    echo 2. Press F4 to open MetaEditor
    echo 3. Navigate to Experts folder
    echo 4. Open BITTEN_Instance[1/2/3].mq5
    echo 5. Press F7 to compile
    echo 6. Attach EA to a chart
    echo.
    echo EA Settings:
    echo Instance 1: MagicNumber=20250626, MaxRisk=2%%, MaxDailyTrades=10
    echo Instance 2: MagicNumber=20250627, MaxRisk=3%%, MaxDailyTrades=20
    echo Instance 3: MagicNumber=20250628, MaxRisk=5%%, MaxDailyTrades=50
    echo.
    echo Use launcher scripts to start each instance:
    echo - Launch_Instance1.bat
    echo - Launch_Instance2.bat
    echo - Launch_Instance3.bat
    echo.
    echo Monitor all instances with: Monitor_BITTEN.bat
) > "README_BITTEN.txt"

echo.
echo =========================================
echo Setup Complete!
echo =========================================
echo.
echo Created:
echo - EA copies for each instance
echo - Configuration files
echo - Launcher scripts
echo - Monitor script
echo - Python config (mt5_config.py)
echo - README_BITTEN.txt
echo.
echo Next: Open each MT5, compile the EA, and attach to charts
echo.
pause