<template>
<description>HydraX BITTEN Chart Template with EA Pre-attached</description>
<window>
<symbol>EURUSD</symbol>
<period>16408</period>
<leftpos>0</leftpos>
<digits>5</digits>
<scale>4</scale>
<graph>1</graph>
<fore>0</fore>
<grid>1</grid>
<volume>1</volume>
<scroll>1</scroll>
<shift>1</shift>
<ohlc>1</ohlc>
<one_click>0</one_click>
<one_click_btn>1</one_click_btn>
<askline>1</askline>
<days>0</days>
<descriptions>0</descriptions>
<tradelines>1</tradelines>
<window_left>26</window_left>
<window_top>26</window_top>
<window_right>1246</window_right>
<window_bottom>698</window_bottom>
<window_type>3</window_type>
<background_color>0</background_color>
<foreground_color>16777215</foreground_color>
<barup_color>65280</barup_color>
<bardown_color>255</bardown_color>
<bullcandle_color>65280</bullcandle_color>
<bearcandle_color>255</bearcandle_color>
<chartline_color>65280</chartline_color>
<volumes_color>32768</volumes_color>
<grid_color>10061943</grid_color>
<askline_color>255</askline_color>
<stops_color>255</stops_color>

<experts>
<expert>
<name>BITTENBridge</name>
<flags>347</flags>
<window_num>0</window_num>
<inputs>
<input>
<name>MagicNumber</name>
<value>20250726</value>
</input>
<input>
<name>LotSize</name>
<value>0.01</value>
</input>
<input>
<name>MaxSpread</name>
<value>5</value>
</input>
<input>
<name>FireFile</name>
<value>fire.txt</value>
</input>
<input>
<name>EnableTrading</name>
<value>true</value>
</input>
</inputs>
</expert>
</experts>

<objects>
</objects>

<indicators>
<indicator>
<name>Moving Average</name>
<path>Examples\Custom Moving Average</path>
<apply>1</apply>
<show_data>1</show_data>
<inputs>
<input>
<name>InpMAPeriod</name>
<value>21</value>
</input>
<input>
<name>InpMAShift</name>
<value>0</value>
</input>
<input>
<name>InpMAMethod</name>
<value>0</value>
</input>
</inputs>
<colors>
<color>255</color>
</colors>
<levels>
</levels>
<width>1</width>
<style>0</style>
<weight>0</weight>
</indicator>
</indicators>
</window>
</template>