#!/bin/bash
# Setup script for testing BITTEN trade alerts

echo "🚀 BITTEN Trade Alert Test Setup"
echo "================================"
echo ""
echo "To test the alerts in your Telegram group, you need:"
echo ""
echo "1. Your Telegram Bot Token"
echo "   - Get from @BotFather on Telegram"
echo "   - Should look like: 123456789:ABCdefGHIjklMNOpqrsTUVwxyz"
echo ""
echo "2. Your Telegram Chat/Group ID" 
echo "   - Add your bot to the group"
echo "   - Send a message in the group"
echo "   - Visit: https://api.telegram.org/bot<YOUR_BOT_TOKEN>/getUpdates"
echo "   - Look for 'chat':{'id': -123456789}"
echo ""
echo "Then run these commands:"
echo ""
echo "export TELEGRAM_BOT_TOKEN='your_bot_token_here'"
echo "export TELEGRAM_CHAT_ID='your_group_id_here'"
echo "python3 test_trade_alerts.py"
echo ""
echo "Example:"
echo "export TELEGRAM_BOT_TOKEN='123456789:ABCdefGHIjklMNOpqrsTUVwxyz'"
echo "export TELEGRAM_CHAT_ID='-1001234567890'"
echo "python3 test_trade_alerts.py"