name: Bug Report
description: File a bug report to help us improve HydraX v2
title: "[Bug]: "
labels: ["bug", "needs-triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true
      
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What did you expect?
    validations:
      required: true
      
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
      
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Core Trading Logic
        - Telegram Bot
        - Flask API
        - MT5 Bridge
        - Configuration
        - Documentation
        - Other
    validations:
      required: true
      
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: What environment are you running?
      placeholder: |
        - OS: [e.g. Ubuntu 20.04]
        - Python version: [e.g. 3.9.7]
        - HydraX version: [e.g. v2.0.1]
        - Browser (if applicable): [e.g. Chrome 91.0.4472.124]
    validations:
      required: true
      
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Please copy and paste any relevant log output.
      render: shell
      
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true