-- BITTEN v2.0 Signals Table
-- Elite Guard generated trading signals with SMC pattern detection

CREATE TABLE IF NOT EXISTS signals (
    signal_id TEXT PRIMARY KEY,
    symbol TEXT NOT NULL,
    direction TEXT NOT NULL CHECK (direction IN ('BUY', 'SELL')),
    entry_price REAL NOT NULL,
    sl_pips REAL NOT NULL,
    tp_pips REAL NOT NULL,
    confidence REAL NOT NULL CHECK (confidence >= 0 AND confidence <= 100),
    citadel_score REAL CHECK (citadel_score >= 0 AND citadel_score <= 10),
    pattern_type TEXT NOT NULL,
    signal_type TEXT CHECK (signal_type IN ('RAPID_ASSAULT', 'PRECISION_STRIKE')),
    session TEXT CHECK (session IN ('LONDON', 'NY', 'ASIAN', 'OVERLAP')),
    created_at TIMESTAMP DEFAULT NOW(),
    expires_at TIMESTAMP,
    status TEXT DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'EXPIRED', 'FIRED', 'CANCELLED'))
);

-- Performance indexes
CREATE INDEX IF NOT EXISTS idx_signals_status_created ON signals(status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_signals_symbol_created ON signals(symbol, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_signals_confidence ON signals(confidence DESC);
CREATE INDEX IF NOT EXISTS idx_signals_pattern_type ON signals(pattern_type);
CREATE INDEX IF NOT EXISTS idx_signals_session ON signals(session);
CREATE INDEX IF NOT EXISTS idx_signals_expires_at ON signals(expires_at) WHERE status = 'ACTIVE';

-- Comments
COMMENT ON TABLE signals IS 'Trading signals generated by Elite Guard SMC pattern detection';
COMMENT ON COLUMN signals.confidence IS 'Total Confluence Score (TCS) 0-100%';
COMMENT ON COLUMN signals.citadel_score IS 'CITADEL Shield validation score 0-10';
COMMENT ON COLUMN signals.pattern_type IS 'LIQUIDITY_SWEEP_REVERSAL, ORDER_BLOCK_BOUNCE, FAIR_VALUE_GAP_FILL, VCB_BREAKOUT, SWEEP_RETURN, MOMENTUM_BURST';
COMMENT ON COLUMN signals.signal_type IS 'RAPID_ASSAULT (tight TP 6-10 pips) or PRECISION_STRIKE (standard TP 20-30 pips)';
