# Intelligence System Configuration

system:
  name: HydraX Intelligence System
  version: 2.0.0
  environment: development
  debug: false

# Cache configuration
cache:
  enabled: true
  backend: hybrid  # memory, redis, or hybrid
  ttl_default: 300
  ttl_signals: 600
  ttl_market_data: 60
  max_size: 10000
  memory_config:
    max_size: 1000
    max_memory: 104857600  # 100MB
  redis_config:
    connection_params:
      url: redis://localhost:6379/0

# Monitoring configuration
monitoring:
  log_level: INFO
  log_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  metrics_enabled: true
  metrics_port: 9090
  performance_tracking: true
  console_logging: true
  file_logging: true
  structured_logs: true
  log_dir: logs/intelligence
  max_log_size: 10485760  # 10MB
  backup_count: 5

# Processing configuration
processing:
  max_workers: 10
  batch_size: 100
  timeout: 300
  retry_count: 3
  retry_backoff: 2.0

# Data pipeline configuration
pipeline:
  buffer_size: 1000
  processing_threads: 4
  max_queue_size: 10000

# Required APIs (for validation)
required_apis:
  - market_data
  - news_feed

# Feature flags
features:
  enable_ml_predictions: false
  enable_sentiment_analysis: true
  enable_pattern_recognition: true
  enable_volume_analysis: true

# Performance tuning
performance:
  max_concurrent_requests: 50
  request_timeout: 30
  connection_pool_size: 20
  keepalive_timeout: 60