# BITTEN Trading Pairs Configuration v5.0 - APEX ENGINE OPTIMIZED
# 15 pairs including volatility monsters for ultra-aggressive trading
# Optimized for APEX v5.0: 40+ signals/day @ 89% win rate
# Last updated: 2025-07-13

# APEX v5.0 Trading pairs with ultra-aggressive TCS settings
trading_pairs:
  
  # MAJOR PAIRS - Core trading with v5.0 optimized TCS
  major_pairs:
    EURUSD:
      pip_value: 0.0001
      min_volume: 0.01
      max_volume: 100.0
      spread_limit: 2.0
      session_hours: 
        - "08:00-17:00"  # London
        - "13:00-22:00"  # NY
      volatility_filter: true
      contract_size: 100000
      min_lot: 0.01
      max_lot: 100
      tcs_requirement: 40  # v5.0 minimum
      v5_boost: 1.1
      v5_tcs_reduction: 2
      category: "major"
      pair_type: "standard"
      description: "Euro vs US Dollar - Major pair"
      
    GBPUSD:
      pip_value: 0.0001
      min_volume: 0.01
      max_volume: 100.0
      spread_limit: 3.0
      session_hours: 
        - "08:00-17:00"  # London focus
        - "13:00-22:00"  # NY
      volatility_filter: true
      contract_size: 100000
      min_lot: 0.01
      max_lot: 100
      tcs_requirement: 40
      v5_boost: 1.2
      v5_tcs_reduction: 3
      category: "major"
      pair_type: "standard"
      description: "British Pound vs US Dollar - Major pair"
      
    USDJPY:
      pip_value: 0.01
      min_volume: 0.01
      max_volume: 100.0
      spread_limit: 2.5
      session_hours: 
        - "00:00-09:00"  # Asian
        - "13:00-22:00"  # NY
      volatility_filter: true
      contract_size: 100000
      min_lot: 0.01
      max_lot: 100
      tcs_requirement: 40
      v5_boost: 1.1
      v5_tcs_reduction: 2
      category: "major"
      pair_type: "standard"
      description: "US Dollar vs Japanese Yen - Major pair"
      
    USDCAD:
      pip_value: 0.0001
      min_volume: 0.01
      max_volume: 100.0
      spread_limit: 2.5
      session_hours: 
        - "13:00-22:00"  # NY focus
      volatility_filter: true
      contract_size: 100000
      min_lot: 0.01
      max_lot: 100
      tcs_requirement: 40
      v5_boost: 1.0
      v5_tcs_reduction: 2
      category: "major"
      pair_type: "commodity"
      description: "US Dollar vs Canadian Dollar - Commodity pair"

  # VOLATILE PAIRS - High-performance with enhanced TCS settings
  volatile_pairs:
    GBPJPY:
      pip_value: 0.01
      min_volume: 0.01
      max_volume: 100.0
      spread_limit: 4.0
      session_hours: 
        - "00:00-09:00"  # Asian
        - "08:00-17:00"  # London
      volatility_filter: true
      contract_size: 100000
      min_lot: 0.01
      max_lot: 100
      tcs_requirement: 40
      v5_boost: 1.3
      v5_tcs_reduction: 5
      category: "volatile"
      pair_type: "volatile"
      description: "British Pound vs Japanese Yen - High volatility"
      
    EURJPY:
      pip_value: 0.01
      min_volume: 0.01
      max_volume: 100.0
      spread_limit: 3.5
      session_hours: 
        - "08:00-17:00"  # London focus
      volatility_filter: true
      contract_size: 100000
      min_lot: 0.01
      max_lot: 100
      tcs_requirement: 40
      v5_boost: 1.2
      v5_tcs_reduction: 4
      category: "volatile"
      pair_type: "volatile"
      description: "Euro vs Japanese Yen - High volatility"
      
    AUDJPY:
      pip_value: 0.01
      min_volume: 0.01
      max_volume: 100.0
      spread_limit: 4.0
      session_hours: 
        - "00:00-09:00"  # Asian focus
      volatility_filter: true
      contract_size: 100000
      min_lot: 0.01
      max_lot: 100
      tcs_requirement: 40
      v5_boost: 1.2
      v5_tcs_reduction: 4
      category: "volatile"
      pair_type: "volatile"
      description: "Australian Dollar vs Japanese Yen - Volatile cross"
      
    GBPCHF:
      pip_value: 0.0001
      min_volume: 0.01
      max_volume: 100.0
      spread_limit: 4.0
      session_hours: 
        - "08:00-17:00"  # European hours
      volatility_filter: true
      contract_size: 100000
      min_lot: 0.01
      max_lot: 100
      tcs_requirement: 40
      v5_boost: 1.1
      v5_tcs_reduction: 3
      category: "volatile"
      pair_type: "volatile"
      description: "British Pound vs Swiss Franc - European volatile"

  # COMMODITY/STANDARD PAIRS - Stable pairs with standard settings
  commodity_pairs:
    AUDUSD:
      pip_value: 0.0001
      min_volume: 0.01
      max_volume: 100.0
      spread_limit: 3.0
      session_hours: 
        - "00:00-09:00"  # Asian focus
      volatility_filter: true
      contract_size: 100000
      min_lot: 0.01
      max_lot: 100
      tcs_requirement: 40
      v5_boost: 1.0
      v5_tcs_reduction: 2
      category: "commodity"
      pair_type: "commodity"
      description: "Australian Dollar vs US Dollar - Commodity pair"
      
    NZDUSD:
      pip_value: 0.0001
      min_volume: 0.01
      max_volume: 100.0
      spread_limit: 3.5
      session_hours: 
        - "00:00-09:00"  # Asian focus
      volatility_filter: true
      contract_size: 100000
      min_lot: 0.01
      max_lot: 100
      tcs_requirement: 40
      v5_boost: 1.0
      v5_tcs_reduction: 2
      category: "commodity"
      pair_type: "commodity"
      description: "New Zealand Dollar vs US Dollar - Commodity pair"
      
    USDCHF:
      pip_value: 0.0001
      min_volume: 0.01
      max_volume: 100.0
      spread_limit: 3.0
      session_hours: 
        - "08:00-17:00"  # European
        - "13:00-22:00"  # NY
      volatility_filter: true
      contract_size: 100000
      min_lot: 0.01
      max_lot: 100
      tcs_requirement: 40
      v5_boost: 1.0
      v5_tcs_reduction: 2
      category: "safe"
      pair_type: "safe"
      description: "US Dollar vs Swiss Franc - Safe haven pair"
      
    EURGBP:
      pip_value: 0.0001
      min_volume: 0.01
      max_volume: 100.0
      spread_limit: 3.0
      session_hours: 
        - "08:00-17:00"  # European focus
      volatility_filter: true
      contract_size: 100000
      min_lot: 0.01
      max_lot: 100
      tcs_requirement: 40
      v5_boost: 1.0
      v5_tcs_reduction: 2
      category: "cross"
      pair_type: "cross"
      description: "Euro vs British Pound - European cross"

  # VOLATILITY MONSTERS - NEW v5.0 Ultra-aggressive pairs
  volatility_monsters:
    GBPNZD:
      pip_value: 0.0001
      min_volume: 0.01
      max_volume: 100.0
      spread_limit: 8.0  # Higher spread tolerance
      session_hours: 
        - "00:00-09:00"  # Asian
        - "08:00-17:00"  # London
      volatility_filter: false  # Allow high volatility
      contract_size: 100000
      min_lot: 0.01
      max_lot: 50  # Reduced max due to volatility
      tcs_requirement: 35  # Ultra low for maximum extraction
      v5_boost: 1.5
      v5_tcs_reduction: 7
      category: "monster"
      pair_type: "monster"
      description: "British Pound vs New Zealand Dollar - 200+ pip daily range"
      risk_multiplier: 1.3
      
    GBPAUD:
      pip_value: 0.0001
      min_volume: 0.01
      max_volume: 100.0
      spread_limit: 6.0
      session_hours: 
        - "00:00-09:00"  # Asian
        - "08:00-17:00"  # London
      volatility_filter: false
      contract_size: 100000
      min_lot: 0.01
      max_lot: 75
      tcs_requirement: 35
      v5_boost: 1.4
      v5_tcs_reduction: 6
      category: "monster"
      pair_type: "monster"
      description: "British Pound vs Australian Dollar - Extreme volatility"
      risk_multiplier: 1.2
      
    EURAUD:
      pip_value: 0.0001
      min_volume: 0.01
      max_volume: 100.0
      spread_limit: 5.0
      session_hours: 
        - "00:00-09:00"  # Asian
        - "08:00-17:00"  # European
      volatility_filter: false
      contract_size: 100000
      min_lot: 0.01
      max_lot: 100
      tcs_requirement: 35
      v5_boost: 1.3
      v5_tcs_reduction: 5
      category: "monster"
      pair_type: "monster"
      description: "Euro vs Australian Dollar - Trending beast"
      risk_multiplier: 1.1

# APEX v5.0 Strategy assignments optimized for ultra-aggressive trading
apex_v5_strategies:
  
  ultra_volume_strategy:
    description: "APEX v5.0 ultra-volume strategy - 40+ signals/day"
    allowed_pairs:
      # All 15 pairs available
      - EURUSD
      - GBPUSD
      - USDJPY
      - USDCAD
      - GBPJPY
      - EURJPY
      - AUDJPY
      - GBPCHF
      - AUDUSD
      - NZDUSD
      - USDCHF
      - EURGBP
      - GBPNZD  # Monster
      - GBPAUD  # Monster
      - EURAUD  # Monster
    min_tcs: 35  # Ultra-aggressive minimum
    target_signals_per_day: 40
    max_signals_per_day: 200
    session_boosts:
      ASIAN: 1.5
      LONDON: 2.0
      NY: 1.8
      OVERLAP: 3.0  # Triple boost
    
  m3_focus_strategy:
    description: "M3 timeframe focus (60% of signals)"
    allowed_pairs:
      - EURUSD
      - GBPUSD
      - USDJPY
      - USDCAD
      - GBPJPY
      - EURJPY
      - AUDJPY
      - GBPCHF
      - AUDUSD
      - NZDUSD
      - USDCHF
      - EURGBP
      - GBPNZD
      - GBPAUD
      - EURAUD
    min_tcs: 35
    timeframe_weights:
      M1: 0.20
      M3: 0.60  # Primary focus
      M5: 0.15
      M15: 0.05
    
  confluence_hunter_strategy:
    description: "Hunt for 2+ pattern confluence signals"
    allowed_pairs:
      - EURUSD
      - GBPUSD
      - USDJPY
      - USDCAD
      - GBPJPY
      - EURJPY
      - AUDJPY
      - GBPCHF
      - AUDUSD
      - NZDUSD
      - USDCHF
      - EURGBP
      - GBPNZD
      - GBPAUD
      - EURAUD
    min_tcs: 40
    confluence_bonus: 25  # +25 TCS for confluence
    ultra_confluence_bonus: 35  # +35 TCS for 4+ patterns

# MT5 Bridge symbol mappings for all 15 pairs
mt5_mappings:
  # Original pairs
  EURUSD: "EURUSD"
  GBPUSD: "GBPUSD"
  USDJPY: "USDJPY"
  USDCAD: "USDCAD"
  GBPJPY: "GBPJPY"
  AUDUSD: "AUDUSD"
  NZDUSD: "NZDUSD"
  EURJPY: "EURJPY"
  AUDJPY: "AUDJPY"
  GBPCHF: "GBPCHF"
  USDCHF: "USDCHF"
  EURGBP: "EURGBP"
  # New volatility monsters
  GBPNZD: "GBPNZD"
  GBPAUD: "GBPAUD"
  EURAUD: "EURAUD"

# APEX v5.0 Enhanced session definitions
apex_v5_sessions:
  asian:
    hours: "22:00-07:00"
    timezone: "UTC"
    boost_multiplier: 1.5
    tcs_reduction: 5
    optimal_pairs:
      - USDJPY
      - AUDUSD
      - NZDUSD
      - AUDJPY
      - EURAUD
      - GBPAUD
      
  london:
    hours: "07:00-12:00"
    timezone: "UTC"
    boost_multiplier: 2.0
    tcs_reduction: 8
    optimal_pairs:
      - GBPUSD
      - EURUSD
      - GBPJPY
      - EURGBP
      - GBPCHF
      - GBPNZD
      - GBPAUD
      
  new_york:
    hours: "12:00-21:00"
    timezone: "UTC"
    boost_multiplier: 1.8
    tcs_reduction: 7
    optimal_pairs:
      - EURUSD
      - GBPUSD
      - USDCAD
      - USDCHF
      - USDJPY
      
  overlap_london_ny:
    hours: "12:00-16:00"
    timezone: "UTC"
    boost_multiplier: 3.0  # TRIPLE BOOST
    tcs_reduction: 10
    optimal_pairs: "ALL"  # All 15 pairs active

# Heat map tracking for all 15 pairs
heat_map_config:
  tracked_pairs:
    - EURUSD
    - GBPUSD
    - USDJPY
    - USDCAD
    - GBPJPY
    - EURJPY
    - AUDJPY
    - GBPCHF
    - AUDUSD
    - NZDUSD
    - USDCHF
    - EURGBP
  volatility_monsters:
    - GBPNZD
    - GBPAUD
    - EURAUD
  update_interval_seconds: 5  # Faster updates for v5.0
  history_retention_days: 30

# APEX v5.0 Risk management settings per pair type
risk_management:
  pair_type_multipliers:
    major: 1.0
    volatile: 1.1
    commodity: 0.9
    safe: 0.8
    cross: 0.9
    monster: 1.3  # Higher risk for monsters
  
  correlation_limits:
    max_usd_exposure: 60.0  # 60% max USD exposure
    max_eur_exposure: 40.0  # 40% max EUR exposure
    max_gbp_exposure: 30.0  # 30% max GBP exposure
    max_jpy_exposure: 25.0  # 25% max JPY exposure
    max_pair_correlation: 70.0  # 70% max correlation

# Configuration metadata
metadata:
  version: "5.0.0"
  engine: "APEX-FX v5.0 FINAL ALL-IN"
  last_updated: "2025-07-13"
  total_active_pairs: 15
  major_pairs_count: 4
  volatile_pairs_count: 4
  commodity_pairs_count: 4
  volatility_monsters_count: 3
  created_by: "APEX v5.0 Configuration System"
  description: "Ultra-aggressive 15-pair system optimized for 40+ signals/day @ 89% win rate"
  target_signals_per_day: 40
  max_signals_per_day: 200
  ultra_aggressive_mode: true
  min_tcs_threshold: 35
  session_boost_enabled: true
  confluence_detection: true